### ISSUE TITLE
describe the current "it is possible to nest functions"

### ISSUE THREAD

**Issue by bjdmeest** [kg-construct/rml-fno-spec#3]
Came from #1

**Comment by bjdmeest** [comment]
The whole 'functions on top of joins' depends on the resolution of #2

**Comment by bjdmeest** [comment]
An example would be, in YARRRML, based on https://rml.io/yarrrml/matey/ Advanced example:

```yaml
prefixes:
  ex: "http://example.com/"

mappings:
  person:
    sources:
      - ['persons.json~jsonpath', '$.persons[*]']
    s: http://example.com/person/$(firstname)
    po:
      - [a, foaf:Person]
      - [ex:name, $(firstname)]
      - p: ex:likes
        o:
         - function: ex:getAfterHash
           parameters:
             - parameter: ex:param1
               value:
                 mapping: movie
                 condition:
                  function: equal
                  parameters:
                    - [str1, $(movie)]
                    - [str2, $(slug)]
  movie:
    sources:
      - ['movies.csv~csv']
    s: http://example.com/movie#$(slug)
    po:
      - [a, schema:Movie]
```

@dachafra did you have something like this in mind?
